<?php

namespace Optimus\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    public function findAllByPattern($pattern){
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'select p
            from OptimusUserBundle:User p
            where p.username like :pattern'
        )->setParameter('pattern','%'.$pattern.'%');

        return $query->getResult();
    }

}
